

name: 'dbt_snowflake_demo_repo'
version: '1.0.0'

profile: 'dbt_snowflake_demo_repo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"




models:
  dbt_snowflake_demo_repo:
    staging:
      +schema: STAGING #name of schmea what the model will use then it created
      #but = defoult dbt settings = old_schema_name.new_schema_name = use macros.
      +materialized: view 
    marts:
      +schema: MART
      +materialized: table
