-- 1. WAREHOUSE
CREATE WAREHOUSE DBT_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- 2. DATABASE
CREATE DATABASE ANALYTICS_DB;
CREATE SCHEMA ANALYTICS_DB.DBT;

-- 3. DBT ROLE
CREATE ROLE DBT_ROLE;

-- 4. RIGHTS for DBT_ROLE
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;

GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS_DB.DBT TO ROLE DBT_ROLE;

GRANT CREATE TABLE ON SCHEMA ANALYTICS_DB.DBT TO ROLE DBT_ROLE;
GRANT CREATE VIEW ON SCHEMA ANALYTICS_DB.DBT TO ROLE DBT_ROLE;
GRANT CREATE STAGE ON SCHEMA ANALYTICS_DB.DBT TO ROLE DBT_ROLE;

-- 5. USER for DBT
CREATE USER DBT_USER
  PASSWORD = '111'
  DEFAULT_ROLE = DBT_ROLE
  DEFAULT_WAREHOUSE = DBT_WH
  DEFAULT_NAMESPACE = ANALYTICS_DB.DBT;

-- 6. ADD ROLE to DBT User
GRANT ROLE DBT_ROLE TO USER DBT_USER;