-- #01: Check status
SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();

-- #02: Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS DBT_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

-- #03: Use it
USE WAREHOUSE DBT_WH;

-- #04: Create DB and Schemas
CREATE DATABASE IF NOT EXISTS ANALYTICS;
USE DATABASE ANALYTICS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MART;


-- #05: Load CSV via UI and Checks
--
-- Check value with csv data set
SELECT COUNT(*) FROM ANALYTICS.RAW.SALES;
-- structure
 


-- #06: Check STAGING.STG_SALES after staging dbt run
SELECT * 
FROM ANALYTICS.STAGING.STG_SALES
LIMIT 20;

-- #07: Check FCT_ORDER_LINES after dbt run
SELECT * 
FROM ANALYTICS.MART.FCT_ORDER_LINES
LIMIT 20;

-- глянуть есть ли invoice > 1 
SELECT 
    invoice_id, 
    COUNT(*) AS cnt
FROM ANALYTICS.MART.FCT_ORDER_LINES
GROUP BY invoice_id
HAVING COUNT(*) > 1;


-- #08: Check FCT_ORDERS after dbt run
SELECT * 
FROM ANALYTICS.MART.FCT_ORDERS
LIMIT 20;

-- глянуть есть ли invoice > 1 
SELECT 
    invoice_id, 
    COUNT(*) AS cnt
FROM ANALYTICS.MART.FCT_ORDERS
GROUP BY invoice_id
HAVING COUNT(*) > 1;

-- #09: Check DIM_CUSTOMER after dbt run
SELECT
    *
FROM ANALYTICS.MART.DIM_CUSTOMER
LIMIT 20;

-- #10: Check DIM_PRODUCT after dbt run
SELECT
    *
FROM ANALYTICS.MART.DIM_PRODUCT
LIMIT 20;

-- #11: Check MART_REVENUE_DAILY
SELECT
    *
FROM ANALYTICS.MART.MART_REVENUE_DAILY
LIMIT 20;

-- #12: Check MART_PRODUCT_PERFORMANCE
SELECT
    *
FROM ANALYTICS.MART.MART_PRODUCT_PERFORMANCE
LIMIT 20;

SELECT
    MIN(cumulative_share) AS min_cum_share,
    MAX(cumulative_share) AS max_cum_share,
    SUM(revenue_share) AS total_revenue_share
FROM ANALYTICS.MART.MART_PRODUCT_PERFORMANCE;

-- #13: Download CSV to import to Power BI
SELECT * FROM ANALYTICS.MART.FCT_ORDERSж

SELECT * FROM ANALYTICS.MART.DIM_CUSTOMER;
SELECT * FROM ANALYTICS.MART.MART_REVENUE_DAILY;
SELECT * FROM ANALYTICS.MART.MART_PRODUCT_PERFORMANCE;

 