version: 2

sources:
  - name: raw
    database: ANALYTICS_DB
    schema: RAW
    description: 'Raw Online Retail sales data loaded into Snowflake'

    tables:
      - name: SALES
        columns:
          - name: INVOICE
            tests:
              - not_null

          - name: STOCKCODE
            tests:
              - not_null

          - name: QUANTITY
            tests:
              - not_null

          - name: INVOICEDATE
            tests:
              - not_null

          - name: PRICE
            tests:
              - not_null
